"""empty message

Revision ID: 883719e44e28
Revises: d5ec9ef629f1
Create Date: 2024-11-09 18:59:07.970731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '883719e44e28'
down_revision = 'd5ec9ef629f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordersproducts')
    op.drop_table('carts')
    op.drop_table('orderspro')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_images_product_id_products'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.drop_column('amount')

    with op.batch_alter_table('orderproducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orderproducts_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_orderproducts_order_id_orders'), 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_product_id_products', type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_order_id_orders'), 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_image_id_images', type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_products_image_id_images', 'images', ['image_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('amount')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_orders_product_id_products', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('orderproducts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orderproducts_order_id_orders'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orderproducts_product_id_products'), type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('email')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_images_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    op.create_table('orderspro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orderspro_pkey')
    )
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_carts_product_id_products'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_carts_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='carts_pkey')
    )
    op.create_table('ordersproducts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ordersproducts_pkey')
    )
    # ### end Alembic commands ###
